name: dotnet format

on:
  push:
    paths:
      - "**/*.cs"
      - ".editorconfig"

jobs:
  check-format:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'
